name: Auto Commit Daily

# Needed so the workflow can push back to your repo
permissions:
  contents: write

on:
  schedule:
    # GitHub cron uses **UTC**. 09:00 IST = 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch: {} # allow manual run from Actions tab

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make a change
        run: |
          echo "$(date -u) UTC" >> activity.log

      - name: Commit & Push
        run: |
          git add activity.log
          git commit -m "chore: automated commit on $(date -u +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
